# Generated by Django 3.2.16 on 2023-03-25 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Allergy',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('allergy_name', models.CharField(blank=True, db_column='allergy_ name', max_length=20, null=True)),
            ],
            options={
                'db_table': 'allergy',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'category',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(blank=True, max_length=20, null=True)),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='menu/')),
            ],
            options={
                'db_table': 'menu',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=45)),
                ('business_hours', models.CharField(blank=True, max_length=20, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('category_name', models.CharField(blank=True, max_length=45, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='restaurant/')),
            ],
            options={
                'db_table': 'restaurant',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=45)),
                ('email', models.CharField(max_length=30, unique=True)),
                ('gender', models.IntegerField(blank=True, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'user',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UserAllergy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allergy', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='jmc.allergy')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='jmc.user')),
            ],
            options={
                'db_table': 'user_allergy',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='review/')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='jmc.menu')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='jmc.user')),
            ],
            options={
                'db_table': 'review',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PreferredMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preference', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='jmc.user')),
            ],
            options={
                'db_table': 'preferred_menu',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='NutritionInformation',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('ingredients', models.CharField(blank=True, max_length=20, null=True)),
                ('weight', models.IntegerField(blank=True, null=True)),
                ('calories', models.IntegerField(blank=True, null=True)),
                ('carbohydrates', models.IntegerField(blank=True, null=True)),
                ('sugar', models.IntegerField(blank=True, null=True)),
                ('protein', models.IntegerField(blank=True, null=True)),
                ('fat', models.IntegerField(blank=True, null=True)),
                ('trans_fat', models.IntegerField(blank=True, null=True)),
                ('saturation_fat', models.IntegerField(blank=True, null=True)),
                ('cholesterol', models.IntegerField(blank=True, null=True)),
                ('sodium', models.IntegerField(blank=True, null=True)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='jmc.menu')),
            ],
            options={
                'db_table': 'nutrition_information',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MenuRecommendLog',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('datetime', models.DateTimeField(blank=True, null=True)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='jmc.menu')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='jmc.user')),
            ],
            options={
                'db_table': 'menu_recommend_log',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MenuAllergy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allergy', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='jmc.allergy')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='jmc.menu')),
            ],
            options={
                'db_table': 'menu_allergy',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='menu',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='jmc.restaurant'),
        ),
    ]
