# Generated by Django 3.2.16 on 2023-03-28 07:44

from django.db import migrations, models
import django.db.models.deletion
import jmc.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Allergy',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('allergy_name', models.CharField(blank=True, db_column='allergy_ name', max_length=20, null=True)),
            ],
            options={
                'db_table': 'allergy',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'category',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('category', models.CharField(blank=True, max_length=20, null=True)),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('emotion', models.CharField(blank=True, max_length=20, null=True)),
                ('weather', models.CharField(blank=True, max_length=20, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=jmc.models.MenuImagePath)),
            ],
            options={
                'db_table': 'menu',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=45)),
                ('business_hours', models.CharField(blank=True, max_length=20, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('category_name', models.CharField(blank=True, max_length=45, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='restaurant/')),
            ],
            options={
                'db_table': 'restaurant',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=45)),
                ('email', models.CharField(max_length=30, unique=True)),
                ('gender', models.IntegerField(blank=True, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'user',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UserAllergy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allergy', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='jmc.allergy')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jmc.user')),
            ],
            options={
                'db_table': 'user_allergy',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=jmc.models.ReviewImagePath)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='jmc.menu')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='jmc.restaurant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jmc.user')),
            ],
            options={
                'db_table': 'review',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PreferredMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preference', models.IntegerField()),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='jmc.menu')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jmc.user')),
            ],
            options={
                'db_table': 'preferred_menu',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='NutritionInformation',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('gram', models.FloatField(blank=True, null=True)),
                ('calorie', models.FloatField(blank=True, null=True)),
                ('carbohydrate', models.FloatField(blank=True, null=True)),
                ('protein', models.FloatField(blank=True, null=True)),
                ('fat', models.FloatField(blank=True, null=True)),
                ('saturatedfat', models.FloatField(blank=True, null=True)),
                ('unsaturatedfat', models.FloatField(blank=True, null=True)),
                ('cholesterol', models.IntegerField(blank=True, null=True)),
                ('sodium', models.IntegerField(blank=True, null=True)),
                ('potash', models.IntegerField(blank=True, null=True)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='jmc.menu')),
            ],
            options={
                'db_table': 'nutrition_information',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MenuRecommendLog',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('datetime', models.DateTimeField(blank=True, null=True)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='jmc.menu')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='jmc.user')),
            ],
            options={
                'db_table': 'menu_recommend_log',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MenuAllergy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allergy', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='jmc.allergy')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='jmc.menu')),
            ],
            options={
                'db_table': 'menu_allergy',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='menu',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='jmc.restaurant'),
        ),
    ]
