# Generated by Django 3.2.16 on 2023-03-25 13:07

from django.db import migrations, models
import jmc.models


class Migration(migrations.Migration):

    dependencies = [
        ('jmc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=jmc.models.MenuImagePath),
        ),
    ]
